### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by jdantonio** [ruby-concurrency/ref#16]
This gem has been downloaded several million times and still does the job extremely well. It's been a while since it's been updated, however. Ruby and its ecosystem have evolved a lot since then. A 2.0 release will give us an opportunity to remove some old code, better leverage the JVM when used with JRuby, and possibly add new features. Below is a list of a few suggestions. All feedback is welcome.

* **Replace compiled Java with JRuby interop:** When running under JRuby the `WeakReference` and `SoftReference` classes are just wrappers around `java.lang.ref.WeakReference` and `java.lang.ref.SoftReference` ([here](https://github.com/ruby-concurrency/ref/blob/master/ext/java/org/jruby/ext/ref/RubyWeakReference.java#L3) and [here](https://github.com/ruby-concurrency/ref/blob/master/ext/java/org/jruby/ext/ref/RubySoftReference.java#L3)). Rather than using compiled code we could use JRuby's excellent interop (as we [frequently do](https://github.com/ruby-concurrency/concurrent-ruby/blob/master/lib/concurrent/atomic/atomic_boolean.rb#L119) in `concurrent-ruby`).
* **Remove support for IronRuby:** IronRuby hasn't been updated [in nearly 4 years](http://ironruby.codeplex.com/releases/view/60511) and appears to no longer be under active development. We can prune some code by removing the [IronRuby-specific code](https://github.com/ruby-concurrency/ref/blob/master/lib/ref/weak_reference/iron_ruby.rb) and default to the pure-Ruby implementation when running under IronRuby.
* **Drop support for Ruby 1.8**
* **Remove any code that checks for the presence of the `Thread` class:** All Ruby interpreters compliant with Ruby 1.9 and above will have threads available. We don't need [code branches](https://github.com/ruby-concurrency/ref/blob/master/lib/ref/safe_monitor.rb#L4) designed for use when threads are not available.
* **Use Ruby's `Monitor` class:** The `SafeMonitor` class in this gem is not thread-safe on all platforms because it depends on [non-atomic operations](https://github.com/ruby-concurrency/ref/blob/master/lib/ref/safe_monitor.rb#L20). The `Monitor` class in Ruby's standard library has [improved since 1.8](http://ruby-doc.org/stdlib-2.1.5/libdoc/monitor/rdoc/Monitor.html) and should now be sufficient.
* **JRuby implementation of `WeakKeyMap`:** Use JRuby interop to wrap [java.util.WeakHashMap](http://docs.oracle.com/javase/7/docs/api/java/util/WeakHashMap.html)
* **Ensure thread-safety:** This gem was originally designed with thread-safety in mind (see aforementioned `SafeMonitor` class) but concurrency is tricky. To my knowledge there have been no thread-safety issues but a full audit never hurts. The Java `WeakReference` and `SoftReference` classes make no thread-safety guarantees (to my knowledge) and some of the classes in this gem perform multiple non-atomic actions in a single method call (see [here](https://github.com/ruby-concurrency/ref/blob/master/lib/ref/abstract_reference_key_map.rb#L31)). We should either ensure that all the classes in the library are thread safe on all platforms, or we should create thread-safe variations.
* **Convert tests to RSpec:** I'll admit it--I'm an RSpec snob. Although this change doesn't really make a difference, it does provide consistency with `concurrent-ruby` which uses RSpec for its tests.

Thoughts? @pitr-ch @mighe @chrisseaton @obrok @lucasallan

**Comment by jdantonio** [comment]
According to the IronLanguages team, IronRuby does appear [to be dead](https://github.com/IronLanguages/main/issues/1160#issuecomment-71476608). Too bad.

**Comment by lucasallan** [comment]
- [x] Remove support for IronRuby
- [ ] Drop support for Ruby 1.8
- [ ] Remove any code that checks for the presence of the Thread class
- [ ] Java implementation of WeakKeyMap
- [x] Use Ruby's Monitor class
- [ ] Ensure thread-safety
- [ ] Convert tests to RSpec

**Comment by pitr-ch** [comment]
If you agree I'll turn these into issues.

**Comment by pitr-ch** [comment]
Thanks @jdantonio

**Comment by jdantonio** [comment]
@lucasallan Is this ready to be released, or is there more work to be done? I don't mind picking up anything that remains.

**Comment by lucasallan** [comment]
@jdantonio it's missing #25 - I haven't had time to work on it yet.

**Comment by jdantonio** [comment]
@lucasallan Thank you! I should have some free time soon. I'll try to take a look at it this weekend.

**Comment by lucasallan** [comment]
@jdantonio Let me know if you can't make it. I might have time next week.
