### ISSUE TITLE
v2.0 Roadmap

### ISSUE THREAD

**Issue by lucasallan** [ruby-concurrency/ref#22]
- [x] Remove support for IronRuby
- [ ] Drop support for Ruby 1.8
- [ ] Remove any code that checks for the presence of the Thread class
- [ ] Java implementation of WeakKeyMap
- [x] Use Ruby's Monitor class
- [ ] Ensure thread-safety
- [ ] Convert tests to RSpec
